"""
Podium quips — friendly, funny one-liners for the leaderboard podium cards.
Quips with {name} will have the player's name substituted at runtime.
Randomly pick 3 at display time; no API call needed.
"""

QUIPS = [
    "Even {name}'s shadow was winning today.",
    "We're checking {name}'s shoes for illegal motors.",
    "{name} didn't just play — {name} performed.",
    "{name}'s warm-up alone was better than most people's full game.",
    "{name}'s paddle is clearly smarter than others.",
    "{name}'s footwork deserves its own highlight reel.",
    "{name}'s game plan was: win. It worked.",
    "{name} came, saw, and pickled everyone.",
    "{name} woke up, chose victory, went back to sleep.",
    "{name} called every shot. And made every shot.",
    "{name} ran to every corner of the court like it was nothing.",
    "Nobody told {name} this was supposed to be hard.",
    "The ball went wherever {name} pointed. Always.",
    "{name} showed up, showed off, showed everyone how it's done.",
    "The court bowed when {name} walked in.",
    "We're not saying {name} cheated. We're just saying… how?",
    "{name}, stop acting like you didn't practise in your sleep.",
    "{name} was too calm to be this good. Suspicious.",
    "The ball has officially filed a complaint against {name}.",
    "{name} scored points we didn't even know were available.",
    "The team's secret weapon — don't tell anyone it's {name}.",
    "You owe the team 7 beers for that finish, {name}.",
    "{name} was solid, steady, and suspiciously consistent.",
    "{name} arrived for the snacks, stayed for the podium.",
    "The podium never looked this good without {name}.",
    "{name} is still figuring out the paddle — and somehow on the podium.",
    "{name} came, saw, pickled.",
    "The ball feared {name} today.",
    "Not all heroes wear capes — {name} carry paddles.",
    "{name} was fuelled entirely by determination and leftover birthday cake.",
    "{name} was officially too good to be invited back next time.",
    "{name} was playing since breakfast and it shows.",
    "Every shot of {name} landed like it had a destination in mind.",
    "We're still replaying {name}'s last smash in our heads.",
    "{name}, Quietly dominant. Very quietly.",
    "The scoreboard struggled to keep up with {name}.",
    "{name} somehow made it look easy. It was not easy.",
    "We'd ask for {name}'s secret but {name} would never tell.",
    "Best smash of the day — and {name} knows it.",
    "The court was {name}'s dance floor today.",
    "{name} came here to have fun and accidentally won everything.",
    "{name} was playing, everyone else was just practising.",
    "The rally that never ended — except it did, in {name}'s favour.",
    "{name} came, {name} saw, {name} politely dominated.",
    "{name}'s backhand alone could win a tournament.",
    "{name} could have done better? Unlikely.",
    "If this were a movie, {name} would be the main character.",
    "{name} played every point like it was the last biscuit on the plate.",
    "Where did that come from? Nobody knows. Not even {name}.",
    "Three words for {name}: natural born winner.",
    "Training? What training? This was pure {name}'s talent.",
    "Even the opponents were secretly cheering for {name}.",
    "Somehow {name} was always in the right place at the right time.",
    "The paddle was just an accessory. {name} didn't need it.",
    "{name} was a walking advertisement for 'just show up and try'.",
    "{name} is officially upgraded from 'player' to 'problem'.",
    "{name}, Zero excuses, maximum results.",
    "{name} is the most dangerous kind: the one who looks relaxed.",
    "{name}'s serve should be registered as a weapon.",
    "{name}, we didn't see that coming. Neither did the ball.",
    "{name} was absolutely unbeatable today. Absolutely.",
    "{name}, your every drop shot today was a poetry",
    "{name} was cool, calm, and absolutely lethal on the court.",
    "{name} won so often today it started feeling normal.",
    "{name} is officially the person everyone wants on their team next time.",
    "The ball couldn't outrun {name}. Nothing could.",
    "If there were bonus points for style, {name} would have won twice.",
    "{name} is always one step ahead. Literally and figuratively.",
    "{name} warmed up and the other team got nervous.",
    "The only thing faster than {name}'s smash was their smile.",
    "Everyone else played. {name} just won.",
    "Somehow even {name}'s mistakes looked intentional.",
    "The ball was scared of {name}. You could tell.",
    "Not here to take part. {name} was here to take over.",
    "{name}, you're just here for the post-game snacks, aren't you?",
    "Wait {name}, how did you get up here?",
    "{name}, you are officially banned from this group.",
    "{name} is technically on the podium. Emotionally in orbit.",
]
