"""
Podium quips — 100 AI generated friendly, funny one-liners for the leaderboard podium cards.
Randomly pick 3 at display time; no API call needed.
"""

QUIPS = [
    "Even their shadow was winning today.",
    "We're checking their shoes for illegal motors.",
    "The team's secret weapon — don't tell anyone.",
    "Solid, steady, and suspiciously consistent.",
    "You owe the team 7 beers for that podium finish.",
    "Arrived for the snacks, stayed for the podium.",
    "The podium never looked this good.",
    "Still figuring out the paddle — and somehow on the podium.",
    "Came, saw, pickled.",
    "The ball feared them today.",
    "Not all heroes wear capes — some carry paddles.",
    "Fuelled entirely by determination and leftover birthday cake.",
    "The court bowed when they walked in.",
    "Their warm-up alone was better than most people's full game.",
    "Officially too good to be invited back next time.",
    "Playing since breakfast and it shows.",
    "Every shot landed like it had a destination in mind.",
    "They didn't just play — they performed.",
    "We're still replaying that last smash in our heads.",
    "Quietly dominant. Very quietly.",
    "You owe the team tequila shots for this win.",
    "The scoreboard struggled to keep up.",
    "Officially banned from this Pickleball group.",
    "Their footwork deserves its own highlight reel.",
    "We're not saying they cheated. We're just saying… how?",
    "The ball went where they pointed. Always.",
    "Somehow made it look easy. It was not easy.",
    "We'd ask for their secret but they'd never tell.",
    "Their paddle is clearly smarter than ours.",
    "Best smash of the day — and they know it.",
    "Woke up, chose victory, went back to sleep.",
    "The court was their dance floor today.",
    "Came here to have fun and accidentally won everything.",
    "Everyone else was just practising.",
    "Playing like they had something to prove. They did.",
    "Too calm to be this good. Suspicious.",
    "The rally that never ended — except it did, in their favour.",
    "They came, they saw, they politely dominated.",
    "Their backhand alone could win a tournament.",
    "Could have done better? Unlikely.",
    "If this were a movie, they'd be the main character.",
    "Played every point like it was the last biscuit on the plate.",
    "Where did that come from? Nobody knows. Not even them.",
    "The ball has officially filed a complaint.",
    "Three words: natural born winner. Okay that's four. Still counts.",
    "Training? What training? This was pure talent.",
    "Even the opponents were secretly cheering for them.",
    "Somehow always in the right place at the right time.",
    "The paddle was just an accessory. They didn't need it.",
    "A walking advertisement for 'just show up and try'.",
    "Officially upgraded from 'player' to 'problem'.",
    "Zero excuses, maximum results.",
    "The most dangerous kind: the one who looks relaxed.",
    "Their serve should be registered as a weapon.",
    "We didn't see that coming. Neither did the ball.",
    "Absolutely unbeatable today. Absolutely.",
    "Every drop shot was poetry. Very painful poetry.",
    "Cool, calm, and absolutely lethal on the court.",
    "There should be a rule about being this good.",
    "Won so often today it started feeling normal.",
    "The court felt shorter when they were on it.",
    "Officially the person everyone wants on their team next time.",
    "Called their shot every time. And made it every time.",
    "Their game plan was: win. It worked.",
    "The ball couldn't outrun them. Nothing could.",
    "Scored points we didn't even know were available.",
    "If there were bonus points for style, they'd have won twice.",
    "Always one step ahead. Literally and figuratively.",
    "They warmed up and the other team got nervous.",
    "Left their best game on the court. Took home the glory.",
    "The only thing faster than their smash was their smile.",
    "Everyone else played. They won.",
    "Today's lesson: never underestimate the quiet ones.",
    "We just witnessed something special. Probably.",
    "Ran to every corner of the court like it was nothing.",
    "Somehow even their mistakes looked intentional.",
    "We're framing the final scoreline and putting it on the wall.",
    "The ball was scared. You could tell.",
    "Showed up, showed off, showed everyone how it's done.",
    "Not here to take part. Here to take over.",
    "You're just here for the post-game snacks, aren't you?",
    "Wait, how did you get up here?",
    "Stop acting like you didn't practise in your sleep.",
]
